# Find the largest Square in an NxM matrix with obstructions

Given an NxM matrix, with zeros and ones (open spaces and obstructions), find the largest sub-matrix, that is square dxd (including 1x1), with no obstructions within it.

## Solution:

Using dynamic programming and memoization we can fill a memoization matrix, of the same size as the input, with previously computed solutions.  

The solution at x, y is the minimum of the previously computed solutions at: 

x+1, y  

x, y+1

x+1, y+1

## Complexity:

We have to touch every element of the input matrix once, so the run-time is O(n X m)

We have to keep a memoization matrix of the same size, so our space complexity is O(n X m)

In [6]:
import numpy as np
# generate matrix for problem
from random import shuffle
def create_nxm_matrix_with_obstructions(n, m, n_obs):
    """ 
    n, m are size of matrix
    n_obs is the number of osbtructions
    """
    mat = np.zeros([n,m])
    indices = [(i,j) for i in range(n) for j in range(m)]
    shuffle(indices)
    for i,j in indices[:n_obs]:
        mat[i][j] = 1
        
    return mat


def find_largest_unobstructed_square(mat):
    n, m  = mat.shape
    mem_mat = np.ones([n,m]) * -1
    maxs = 0
    maxs_x = 0
    maxs_y = 0
    
    def solve(x, y):
        nonlocal n, m, mat, mem_mat, maxs, maxs_x, maxs_y

        if y > n - 1 or x > m - 1:
            return 0
        
        if not mem_mat[y][x] == -1:
            # we've computed this before, so use memo
            return mem_mat[y][x]
        
        # base case
        if y - 1 == n or y - 1 == m:
            # we hit the edge
            if mat[y][x] == 1:
                res = 0
            else:
                res = 1
                
        elif mat[y][x] == 0:
            # recurse three neighbors, take min of those solutions
            s1 = solve(x+1, y)
            s2 = solve(x, y+1)
            s3 = solve(x+1, y+1)
            res = min(s1, s2, s3)
            if res > 0:
                if y + res < n - 1 and x + res < m - 1:
                    res += 1
            else:
                # base case
                res = 1
        else:
            # recurse three neighbors
            solve(x+1, y)
            solve(x, y+1)
            solve(x+1, y+1)
            res = 0
        
        if res > maxs:
            maxs = res
            maxs_x = x
            maxs_y = y
        
        mem_mat[y][x] = res
        
        return res
    
    
    solve(0, 0)
    print("For input matrix:")
    print(mat)
    print("")
    print("Largest square has size of {0}, starting at x = {1} and y = {2}".format(maxs, maxs_x, maxs_y))
    print("")
    print("The Memo. matrix looks like: ")
    print(mem_mat)

In [7]:
n = 10
m = 8
n_obs = 8
mat = create_nxm_matrix_with_obstructions(n, m, n_obs)

find_largest_unobstructed_square(mat)

For input matrix:
[[ 0.  1.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]

Largest square has size of 6.0, starting at x = 1 and y = 1

The Memo. matrix looks like: 
[[ 1.  0.  0.  4.  3.  2.  1.  1.]
 [ 4.  6.  5.  4.  3.  2.  1.  0.]
 [ 3.  5.  5.  4.  3.  2.  1.  1.]
 [ 2.  4.  4.  4.  3.  2.  1.  1.]
 [ 1.  4.  3.  3.  3.  2.  1.  1.]
 [ 0.  3.  3.  2.  2.  2.  1.  1.]
 [ 0.  3.  2.  2.  1.  1.  1.  1.]
 [ 2.  2.  2.  1.  1.  0.  1.  1.]
 [ 1.  1.  1.  1.  0.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.]]
